const pool = require('../config/db');

// @desc    Verify QR code and mark entry/exit
// @route   POST /api/guard/scan
// @access  Private (Guard)
const verifyAndScan = async (req, res) => {
    const { qr_data } = req.body;

    if (!qr_data) {
        return res.status(400).json({ message: 'No QR data provided' });
    }

    try {
        let data;
        try {
            data = JSON.parse(qr_data);
        } catch (e) {
            return res.status(400).json({ message: 'Invalid QR format' });
        }

        const { leave_id, student_id } = data;

        // 1. Get Leave and Student Details
        const [leaveRows] = await pool.query(`
            SELECT lr.*, u.full_name, u.email, s.enrollment_number, s.room_number, s.department
            FROM leave_requests lr
            JOIN students s ON lr.student_id = s.student_id
            JOIN users u ON s.user_id = u.user_id
            WHERE lr.leave_id = ? AND s.student_id = ?
        `, [leave_id, student_id]);

        if (leaveRows.length === 0) {
            return res.status(404).json({ message: 'Leave request not found' });
        }

        const leave = leaveRows[0];

        // 2. Check if leave is approved
        if (leave.current_status !== 'approved') {
            return res.status(400).json({ message: `Leave is not approved. Current status: ${leave.current_status}` });
        }

        // 3. Get or Create Gate Pass
        const [passRows] = await pool.query('SELECT * FROM gate_passes WHERE leave_id = ?', [leave_id]);
        let pass;

        if (passRows.length === 0) {
            // Should have been generated by student, but we can auto-generate if missing/valid
            const [result] = await pool.query(
                'INSERT INTO gate_passes (leave_id, student_id, qr_code) VALUES (?, ?, ?)',
                [leave_id, student_id, qr_data]
            );
            const [newPass] = await pool.query('SELECT * FROM gate_passes WHERE pass_id = ?', [result.insertId]);
            pass = newPass[0];
        } else {
            pass = passRows[0];
        }

        let action = '';
        let updateQuery = '';
        let updateParams = [];

        // 4. Determine Action: Exit or Return
        if (!pass.scan_out) {
            // First scan = Exit
            action = 'EXIT';
            updateQuery = 'UPDATE gate_passes SET scan_out = NOW(), status = "used" WHERE pass_id = ?';
            updateParams = [pass.pass_id];
        } else if (!pass.scan_in) {
            // Second scan = Return
            action = 'RETURN';
            updateQuery = 'UPDATE gate_passes SET scan_in = NOW(), status = "used" WHERE pass_id = ?';
            updateParams = [pass.pass_id];
        } else {
            return res.status(400).json({
                message: 'This pass has already been used for both Exit and Return',
                student: leave.full_name,
                exit_time: pass.scan_out,
                return_time: pass.scan_in
            });
        }

        await pool.query(updateQuery, updateParams);

        res.json({
            message: `Successfully marked ${action}`,
            action,
            student: {
                name: leave.full_name,
                enrollment: leave.enrollment_number,
                department: leave.department,
                room: leave.room_number
            },
            leave: {
                type: leave.leave_type,
                from: leave.from_date,
                to: leave.to_date
            }
        });

    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error during scan' });
    }
};

module.exports = { verifyAndScan };
